# Generated by Django 4.2.3 on 2023-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (1, "HOD"),
                    (2, "Chef"),
                    (3, "Staff"),
                    (4, "Secretaire"),
                    (5, "Vigil"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
