# Generated by Django 4.2.3 on 2023-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretaire",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="vigil",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="vigil",
            name="salary",
        ),
        migrations.AddField(
            model_name="staff",
            name="status",
            field=models.CharField(default=1, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "Staff"), (3, "Vigil")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Chef",
        ),
        migrations.DeleteModel(
            name="Secretaire",
        ),
    ]
