# Generated by Django 4.2.3 on 2023-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0003_alter_directory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="email",
            field=models.EmailField(default="", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="directory",
            name="phone_number",
            field=models.CharField(default="", max_length=150, null=True),
        ),
    ]
