# Generated by Django 4.2.3 on 2023-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0004_alter_directory_email_alter_directory_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="email",
            field=models.EmailField(
                default="noreply@codesria.org", max_length=254, null=True, unique=True
            ),
        ),
    ]
