# Generated by Django 4.2.3 on 2023-07-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0005_alter_vigil_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="InOutStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("enter", models.TimeField(default="", null=True)),
                ("exit", models.TimeField(default="", null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.staff"
                    ),
                ),
            ],
        ),
    ]
