# Generated by Django 4.2.3 on 2023-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_out", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inoutstaff",
            name="enter",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
