# Generated by Django 4.2.3 on 2023-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_out", "0002_alter_inoutstaff_enter"),
    ]

    operations = [
        migrations.AddField(
            model_name="inoutstaff",
            name="comment",
            field=models.TextField(default="", null=True),
        ),
    ]
