# Generated by Django 4.2.3 on 2023-07-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretaryvalidate",
            name="purchase_recept",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.invoice",
            ),
        ),
    ]
