# Generated by Django 4.2.3 on 2023-07-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_signature"),
        ("purchase", "0002_alter_secretaryvalidate_purchase_recept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretaryvalidate",
            name="signature",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.signature",
            ),
        ),
    ]
