# Generated by Django 4.2.3 on 2023-07-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_signature"),
        ("purchase", "0003_alter_secretaryvalidate_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="signature",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.signature",
            ),
        ),
        migrations.AddField(
            model_name="staffleave",
            name="signature",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.signature",
            ),
        ),
    ]
