# Generated by Django 4.2.3 on 2023-07-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0007_invoice_secretary_recept_voucher_accountcredit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="client",
            field=models.ForeignKey(
                default=1000,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchase.fournisseur",
            ),
        ),
    ]
