# Generated by Django 4.2.3 on 2023-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0008_voucher_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="marche",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="modalitedepaiement",
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="object",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
