# Generated by Django 4.2.3 on 2023-08-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0009_invoice_marche_invoice_modalitedepaiement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date_livraison",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="imputation",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
